### PR TITLE
yaml file for Linux environment

### PR DESCRIPTION
**Pull request by Gracesta**
`yaml` file for the Linux environment.
(And those minor fixes in my previous PR)

It might not be the minimal environment settings but works on my Linux machine :)

### CODE REVIEW

**Comment by umair-nasir14** [comment]
Thanks for the pull request. I think let's take it to the point where the project works completely with Linux.

**Comment by umair-nasir14** [comment]
Hi @Gracesta! Were you able to confirm if environment_linux.yml works? Also probably imports will need to change for linux.

**Comment by Gracesta** [comment]
Hi @umair-nasir14 
I confirmed `environment_linux.yml` works in my Linux machine. As it was directly exported from my conda environment, it would work I think.

**Comment by umair-nasir14** [comment]
That is awesome! :)

Did you manage to run the whole Word2World loop on your Linux machine?

**Comment by Gracesta** [comment]
Yes!

I first ran `main.py `to generate json file and then ran `play_game.py` to test the generated game stage :)

**Comment by umair-nasir14** [comment]
Apologies @Gracesta for replying late! I am drowned in deadlines. 

Sounds fantastic that it worked! :)

I will review it in a couple of days and then accept it. Meanwhile, it would be awesome if you could post the video of the LLM agent playing the game that you created :)

**Comment by Gracesta** [comment]
Hi, it's never late!

> it would be awesome if you could post the video of the LLM agent playing the game that you created

Do we have such a LLM agent to auto-test created stage? I just tested using my hand :)

**Comment by umair-nasir14** [comment]
Hey, @Gracesta, been a very busy week!

> Hi, it's never late!

Thanks!

> Do we have such a LLM agent to auto-test created stage? I just tested using my hand :)

Yes, we do! :) and it makes a video of the agent playing the game.

**Review by umair-nasir14 — COMMENTED** [review]
This looks all good!

**Comment by Gracesta** [comment]
Hi, @umair-nasir14 !

> Yes, we do! :) and it makes a video of the agent playing the game.

Maybe we're talking about the `mp4` file generated with json file in `output` folder?
I tried but couldn't open it, and it's just only 8bytes.

**Comment by umair-nasir14** [comment]
Hi @Gracesta!

It should open, it is just an mp4 file. It should be a small file because tile size is 16 x 16 and maybe it made a smaller world.

**Pull request merged**
